IO = 'IO'

SAVE_IMG_DIR = 'SAVE_IMG_DIR'
SAVE_DATA_DIR = 'SAVE_DATA_DIR'

LOAD_IMG_DIR = 'LOAD_IMG_DIR'
LOAD_IMG_NAMES = 'LOAD_IMG_NAMES'

SAS_GEOMETRY = 'SAS_GEOMETRY'
THETA_START = 'THETA_START'
THETA_STOP = 'THETA_STOP'
THETA_STEP = 'THETA_STEP'
R = 'R'
Z_TX = 'Z_TX'
Z_RX = 'Z_RX'

SCENE_DIMENSIONS = 'SCENE_DIMENSIONS'
DIM_X  = 'DIM_X'
DIM_Y = 'DIM_y'
DIM_Z = 'DIM_Z'
PIX_DIM = 'PIX_DIM'

BEAMFORMER = 'BEAMFORMER'
r = 'r'

WAVEFORM_SNR = 'WAVEFORM_SNR'
PSNR = 'PSNR'