IO = 'IO'

SAVE_IMG_DIR = 'SAVE_IMG_DIR'
SAVE_DATA_DIR = 'SAVE_DATA_DIR'

LOAD_IMG_DIR = 'LOAD_IMG_DIR'
LOAD_IMG_NAMES = 'LOAD_IMG_NAMES'

SAS_GEOMETRY = 'SAS_GEOMETRY'
THETA_START = 'THETA_START'
THETA_STOP = 'THETA_STOP'
THETA_STEP = 'THETA_STEP'
R = 'R'
Z_TX = 'Z_TX'
Z_RX = 'Z_RX'

SCENE_DIMENSIONS = 'SCENE_DIMENSIONS'
DIM_X  = 'DIM_X'
DIM_Y = 'DIM_y'
DIM_Z = 'DIM_Z'
PIX_DIM = 'PIX_DIM'

BEAMFORMER = 'BEAMFORMER'
r = 'r'

WAVEFORM_SNR = 'WAVEFORM_SNR'
PSNR = 'PSNR'

WAVEFORM = 'WAVEFORM'
T_START = 'T_START'
T_STOP = 'T_STOP'
F_START = 'F_START'
F_STOP = 'F_STOP'
TUKEY_RATIO = 'TUKEY_RATIO'

SIGNAL_PROCESSING = 'SIGNAL_PROCESSING'
FS = 'FS'
C = 'C'

INR = 'INR'
USE = 'USE'
KAPPA = 'KAPPA'
NF = 'NF'
LR = 'LR'
MAX_ITER = 'MAX_ITER'
MOMENTUM = 'MOMENTUM'

GD = 'GD'

GD_TV = 'GD_TV'
REG = 'REG'
REG_WEIGHT = 'REG_WEIGHT'

GD_GRAD_REG = 'GD_GRAD_REG'

DIP = 'DIP'

WIENER = 'WIENER'
MIN_LOG = 'MIN_LOG'
MAX_LOG = 'MAX_LOG'
NUM_LOG_SPACE = 'NUM_LOG_SPACE'

BREMEN = 'BREMEN'

SAVE_EVERY = 'SAVE_EVERY'